all: assignment3.pdf

assignment3.pdf: assignment3.tex pictures
	xelatex assignment3.tex
	xelatex assignment3.tex

pictures: p1.pdf p2.pdf p3.pdf p4.pdf p5.pdf

p1.pdf: p1.asy
	asy p1

p2.pdf: p2.asy
	asy p2

p3.pdf: p3.asy
	asy p3

p4.pdf: p4.asy
	asy p4

p5.pdf: p5.asy
	asy p5
